spring.application.name=studentDetailsSystem

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=studentsdb
spring.data.mongodb.auto-index-creation=true

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/student_security
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true