spring.application.name=studentDetailsSystem

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=studentsdb
spring.data.mongodb.auto-index-creation=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

